name: build-win-package

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build portable exe
        run: |
          pyinstaller --noconfirm --onefile --name mhxy-bot-win10 --add-data "app/ui;app/ui" app/launcher.py

      - name: Setup Inno Setup
        run: choco install innosetup -y

      - name: Build installer
        shell: powershell
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "build\mhxy-bot-win10.iss"

      - name: Upload portable exe
        uses: actions/upload-artifact@v4
        with:
          name: mhxy-bot-win10-portable-exe
          path: dist/mhxy-bot-win10.exe

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: mhxy-bot-win10-installer
          path: dist-installer/mhxy-bot-win10-setup.exe
